### ISSUE TITLE
Segfault caused in ua_processvariable::getValue_Array_double

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#44]
This looks a bit like #31.:

<pre>
#0  0x00007f778c1b1478 in malloc_consolidate (av=av@entry=0x7f7760000020) at malloc.c:4175
#1  0x00007f778c1b4cde in _int_malloc (av=av@entry=0x7f7760000020, bytes=bytes@entry=131072) at malloc.c:3450
#2  0x00007f778c1b7184 in __GI___libc_malloc (bytes=131072) at malloc.c:2913
#3  0x00007f778caa9e78 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f778faf1a43 in __gnu_cxx::new_allocator<double>::allocate (this=0x7f777a7fbb10, __n=16384) at /usr/include/c++/5/ext/new_allocator.h:104
#5  std::allocator_traits<std::allocator<double> >::allocate (__a=..., __n=16384) at /usr/include/c++/5/bits/alloc_traits.h:491
#6  std::_Vector_base<double, std::allocator<double> >::_M_allocate (this=0x7f777a7fbb10, __n=16384) at /usr/include/c++/5/bits/stl_vector.h:170
#7  std::vector<double, std::allocator<double> >::_M_allocate_and_copy<__gnu_cxx::__normal_iterator<double const*, std::vector<double, std::allocator<double> > > > (this=0x7f777a7fbb10, __last=..., __first=..., __n=16384) at /usr/include/c++/5/bits/stl_vector.h:1224
#8  std::vector<double, std::allocator<double> >::operator= (this=this@entry=0x7f777a7fbb10, __x=...) at /usr/include/c++/5/bits/vector.tcc:195
#9  0x00007f778fae9f82 in ua_processvariable::getValue_Array_double (this=this@entry=0x987f9a0) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/ua_processvariable.cpp:219
#10 0x00007f778faea1cd in ua_readproxy_ua_processvariable_getValue_Array_double (handle=0x987f9a0, nodeid=..., includeSourceTimeStamp=<optimized out>, range=<optimized out>, value=0x7f777a7fbc40)
    at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/ua_processvariable.cpp:218
#11 0x00007f778fb18570 in readValueAttributeFromDataSource (rangeptr=0x0, timestamps=UA_TIMESTAMPSTORETURN_SOURCE, v=0x7f777a7fbc40, vn=0x9884188) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/open62541.c:20487
#12 readValueAttributeComplete (server=<optimized out>, v=0x7f777a7fbc40, indexRange=0x7f777a7fbcc0, timestamps=UA_TIMESTAMPSTORETURN_SOURCE, vn=0x9884188) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/open62541.c:20513
#13 Service_Read_single (server=<optimized out>, session=<optimized out>, timestamps=UA_TIMESTAMPSTORETURN_SOURCE, id=0x7f777a7fbca0, v=0x7f777a7fbc40) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/open62541.c:20784
#14 0x00007f778fb18dda in UA_MoniteredItem_SampleCallback (server=0x7c7f180, monitoredItem=0x7f7760004cc0) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/open62541.c:23641
#15 0x00007f778fb2500b in processRepeatedJobs (dispatched=<synthetic pointer>, current=13836136266325, server=0x7c7f180) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/open62541.c:18175
#16 UA_Server_run_iterate (server=0x7c7f180, waitInternal=waitInternal@entry=true) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/open62541.c:18521
#17 0x00007f778faf7322 in ua_uaadapter::workerThread (this=0x7c7ed70) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/ua_adapter.cpp:207
#18 0x00007f778fad7bd6 in ipc_managed_object_callWorker (theClass=<optimized out>) at /build/libchimeratk-controlsystemadapter-opcuaadapter-01.09xenial1.00/src/ipc_managed_object.cpp:27
#19 0x00007f778cad4c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007f778e42c6ba in start_thread (arg=0x7f777a7fc700) at pthread_create.c:333
#21 0x00007f778c23a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
</pre>

But this time the problem is not in `ua_readproxy_ua_processvariable_getValue_string` but in `ua_readproxy_ua_processvariable_getValue_Array_double`.

**Comment by zenker** [comment]
Not observed any more.
